apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deployment
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{.Values.namespace.name}}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          image: {{.Values.namespace.name}}:{{.Values.namespace.name}}
          imagePullPolicy: {{.Values.namespace.name}}
          ports:
            - containerPort: {{.Values.namespace.name}}
          resources:
              requests:
                memory: {{.Values.namespace.name}}
                cpu: {{.Values.namespace.name}}
              limits:
                memory: {{.Values.namespace.name}}
                cpu: {{.Values.namespace.name}}
          livenessProbe:
            path: {{.Values.namespace.name}}
            port: {{.Values.namespace.name}}
          readinessProbe:
           httpGet:
           Path: {{.Values.namespace.name}}
           Port: {{.Values.namespace.name}}