apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{.Values.namespace.name}}
spec:
  type: {{.Values.namespace.name}}
  selector:
    app: techtrends
  ports:
    - protocol: {{.Values.namespace.name}}
      port: {{.Values.namespace.name}}
      targetPort: {{.Values.namespace.name}}