apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-techtrends-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/axiang719/project_1.git"
    path: project/helm
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true